version: '3.8'

services:
  redis:
    image: redis:alpine

  backend:
    build: C:/Users/faj_a/Desktop/devops-docker/material-applications/example-backend
    image: backend-project
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - db

  frontend:
    build: C:/Users/faj_a/Desktop/devops-docker/material-applications/example-frontend
    image: frontend-project
  
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
        - ./database:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  db:
  nginx: